
services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    hostname: rabbitmq-host
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Management UI
      - "1883:1883"  # MQTT (optional)
    volumes:
      # - ./rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=secret
      - RABBITMQ_DEFAULT_VHOST=/
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped


  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb
    hostname: timescaledb-host
    ports:
      - "5433:5432"  # Internal PostgreSQL port remains 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=sensor_data
    volumes:
      - ./init_timescale.sql:/docker-entrypoint-initdb.d/init.sql  # Auto-execute
    #   - ./timescaledb_data:/var/lib/postgresql/data
    restart: unless-stopped


  supabase-postgres:
    image: supabase/postgres:17.4.1.014
    container_name: supabase-postgres
    hostname: supabase-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=supabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      # - POSTGRES_CUSTOM_CONFIG=/etc/postgresql-custom.conf
    volumes:
      - ./init_supabase.sql:/docker-entrypoint-initdb.d/init_supabase.sql:ro  # Auto-execute
      # - ./postgresql.conf:/etc/postgresql-custom.conf:ro
  # Mount custom config
    #  - ./supabase_data:/var/lib/postgresql/data
    restart: unless-stopped
  

  supabase-realtime:
    image: supabase/realtime:v2.34.46
    container_name: supabase-realtime
    hostname: supabase-realtime-host
    ports:
      - "4000:4000"  # Realtime API
    environment:
      - DB_HOST=supabase-postgres  # Use the hostname of the supabase-postgres container
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secret  # Matches supabase-postgres
      - DB_NAME=supabase
      - DB_SSL=false
      - JWT_SECRET=your_super_secret_jwt_32_chars_or_more  # For auth
      - API_JWT_SECRET=your_api_secret_32_chars_or_more     # For API calls
      - SECRET_KEY_BASE=your_generated_64_character_key_here
      - APP_NAME=hotelSensorsManagement
      - PORT=4000
      - SECURE_CHANNELS=true  # Enable for production
      - RLIMIT_NOFILE=1048576  # Set the variable
      - FLY_ALLOC_ID=
      - FLY_APP_NAME=
      - RELEASE_DISTRIBUTION=none  # Disable clustering
      - LIBCLUSTER_ENABLED=false  # Disable clustering
    depends_on:
      - supabase-postgres
    restart: unless-stopped
    
networks:
  default:
    name: supabase-network
    driver: bridge

  # sensors_publisher:
  #   build:
  #     context: ..
  #   container_name: sensors_publisher
  #   command: ["python", "sensors_publisher.py"]
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   restart: unless-stopped

  # sensors_subscriber:
  #   build:
  #     context: ..
  #   container_name: sensors_subscriber
  #   command: ["python", "sensors_subscriber.py"]
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   restart: unless-stopped