
services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    hostname: rabbitmq-host
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Management UI
      - "1883:1883"  # MQTT (optional)
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_DEFAULT_USER= admin
      - RABBITMQ_DEFAULT_PASS= secret
      - RABBITMQ_DEFAULT_VHOST= /
    restart: unless-stopped
